<?php

namespace Ucard\XingdaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * testRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class testRepository extends EntityRepository
{
}
