<?php

namespace XingdaTest\aTestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * learn_symfonyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class learn_symfonyRepository extends EntityRepository
{
}
